$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

Write-Host "Setting up Downloadable..."
function Add-DownloadableToolPath {
  $links = Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Links"
  if (Test-Path -LiteralPath $links) {
    $entries = $env:PATH -split ";"
    if ($entries -notcontains $links) { $env:PATH = "$links;$env:PATH" }
  }
  if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
    $packages = Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Packages"
    if (Test-Path -LiteralPath $packages) {
      $ffmpeg = Get-ChildItem -LiteralPath $packages -Directory -Filter "Gyan.FFmpeg*" -ErrorAction SilentlyContinue |
        ForEach-Object { Get-ChildItem -LiteralPath $_.FullName -Recurse -File -Filter "ffmpeg.exe" -ErrorAction SilentlyContinue } |
        Select-Object -First 1
      if ($ffmpeg) { $env:PATH = "$($ffmpeg.DirectoryName);$env:PATH" }
    }
  }
}

Add-DownloadableToolPath
if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
  throw "ffmpeg is required. Install it with winget install Gyan.FFmpeg, then run setup.cmd again."
}

$launcher = Get-Command py -ErrorAction SilentlyContinue
if ($launcher) {
  & $launcher.Source -3 -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)"
  if ($LASTEXITCODE -ne 0) { throw "Python 3.11 or newer is required." }
  & $launcher.Source -3 -m venv .venv
} else {
  $launcher = Get-Command python -ErrorAction SilentlyContinue
  if (-not $launcher) { throw "Python 3.11 or newer is required. Install it with winget install Python.Python.3.11." }
  & $launcher.Source -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)"
  if ($LASTEXITCODE -ne 0) { throw "Python 3.11 or newer is required." }
  & $launcher.Source -m venv .venv
}
if ($LASTEXITCODE -ne 0 -or -not (Test-Path ".venv\Scripts\python.exe")) { throw "Python could not create the local environment." }
& ".venv\Scripts\python.exe" -m pip install --upgrade pip yt-dlp mutagen
if ($LASTEXITCODE -ne 0) { throw "Python packages could not be installed." }

if (-not (Test-Path .helper-token)) {
  $token = (& ".venv\Scripts\python.exe" -c "import secrets; print(secrets.token_urlsafe(32))").Trim()
  Set-Content -Path .helper-token -Value $token -NoNewline
} else {
  $token = (Get-Content .helper-token -Raw).Trim()
}
Set-Content -Path extension\config.js -Value "// Generated by setup.ps1.`nglobalThis.HELPER_TOKEN = `"$token`";"

$taskName = "Downloadable Helper"
$powershellPath = Join-Path $env:WINDIR "System32\WindowsPowerShell\v1.0\powershell.exe"
$taskAction = New-ScheduledTaskAction -Execute $powershellPath -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File `"$PSScriptRoot\start.ps1`""
$taskTrigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
$taskPrincipal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited
Register-ScheduledTask -TaskName $taskName -Action $taskAction -Trigger $taskTrigger -Principal $taskPrincipal -Force | Out-Null
Start-ScheduledTask -TaskName $taskName

Write-Host "Setup complete. Open chrome://extensions, enable Developer mode, and Load unpacked:"
Write-Host "$PSScriptRoot\extension"
Write-Host "The helper is now running in the background and will start when you sign in."
Write-Host "Use start.cmd only when you want to see diagnostic output."
