#!/bin/zsh
set -euo pipefail

PROJECT_DIR="${0:A:h}"
cd "$PROJECT_DIR"

echo "Setting up the local downloader…"
if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "ffmpeg is required but was not found."
  echo "Install it with Homebrew using: brew install ffmpeg"
  read -k 1 "?Press any key to close…"
  echo
  exit 1
fi

/usr/bin/python3 -m venv .venv
.venv/bin/python -m pip install --upgrade pip yt-dlp mutagen

if [[ -s .helper-token ]]; then
  IFS= read -r TOKEN < .helper-token
else
  TOKEN=$(.venv/bin/python -c 'import secrets; print(secrets.token_urlsafe(32))')
  printf '%s\n' "$TOKEN" > .helper-token
fi
chmod 600 .helper-token
printf '// Generated by setup.command.\nglobalThis.HELPER_TOKEN = "%s";\n' "$TOKEN" > extension/config.js

RUNTIME_DIR="/Users/downloadable/Library/Application Support/PersonalMediaDownloader"
LAUNCH_AGENT="/Users/downloadable/Library/LaunchAgents/com.downloadable.personal-media-downloader.plist"
mkdir -p "$RUNTIME_DIR" "/Users/downloadable/Library/LaunchAgents" "/Users/downloadable/Library/Logs"
rsync -a .venv helper .helper-token "$RUNTIME_DIR/"
cp com.downloadable.personal-media-downloader.plist "$LAUNCH_AGENT"
launchctl bootout "gui/$(id -u)/com.downloadable.personal-media-downloader" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$LAUNCH_AGENT"
launchctl enable "gui/$(id -u)/com.downloadable.personal-media-downloader"
launchctl kickstart -k "gui/$(id -u)/com.downloadable.personal-media-downloader"

chmod +x start.command
echo
echo "Setup complete."
echo "Next: open chrome://extensions, enable Developer mode, and load this folder:"
echo "$PROJECT_DIR/extension"
echo
echo "The local helper is installed as an automatic background service."
if [[ -t 0 ]]; then
  read -k 1 "?Press any key to close…"
  echo
fi
