$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

Write-Host "Setting up Downloadable..."
if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
  throw "ffmpeg is required. Install it with winget install Gyan.FFmpeg, then run setup.ps1 again."
}

py -m venv .venv
& ".venv\Scripts\python.exe" -m pip install --upgrade pip yt-dlp mutagen

if (-not (Test-Path .helper-token)) {
  $token = (& ".venv\Scripts\python.exe" -c "import secrets; print(secrets.token_urlsafe(32))").Trim()
  Set-Content -Path .helper-token -Value $token -NoNewline
} else {
  $token = (Get-Content .helper-token -Raw).Trim()
}
Set-Content -Path extension\config.js -Value "// Generated by setup.ps1.`nglobalThis.HELPER_TOKEN = `"$token`";"

Write-Host "Setup complete. Open chrome://extensions, enable Developer mode, and Load unpacked:"
Write-Host "$PSScriptRoot\extension"
Write-Host "Keep start.ps1 running while downloading."
